== Introduction

ISO 32000-2 introduced the mechanism for defining namespaces within a
logically structured PDF document; identified two recognized namespaces
for tagged PDF documents; and provided strict hierarchical inclusion
rules for the standard structure namespace for PDF 2.0. However, ISO
32000-2 did not specify restrictions and inclusion rules for the
standard structure namespace for PDF 1.7. This document extends the
hierarchical inclusion rules to address both the standard structure
namespace for PDF 2.0 and the standard structure namespace for PDF 1.7.

The primary purpose of this document is to extend the rules already
defined within ISO 32000-2 to resolve any ambiguity.

Document management — Portable Document Format — PDF 1.7 and 2.0
structure namespace inclusion in ISO 32000‑2

The PDF Association may maintain an ongoing series of application notes for guiding developers and users of this document. These application notes are available at https://www.pdfa.org/. The PDF Association will also retain copies of the specific non-ISO normative references of this document which are publicly available electronic documents.

