[[declaration]]
== Declaration of conformance

This document defines additional requirements that are fully compliant
with ISO 32000-2. As such, a PDF document can conform to all the
requirements of ISO 32000-2 and the requirements defined in this
document, retaining compliance with both standards. However, not all
files which are compliant with ISO 32000-2 will be compliant with this
document.

To enable interchange and to identify that a given PDF document conforms
to the requirements defined in this document, that PDF document may
include a PDF declaration of conformance with this document. When such a
PDF declaration is present, it shall conform to the requirements of the
PDF Declarations specification. Such claim of conformance shall take the
form described in <<conformance-declaration>>.

[[conformance-declaration]]
.Declaration of conformance to this document
[width="100%",cols="27%,73%",options="header",]
|===
|*Key* |*Type*
|URI identifier |http://pdfa.org/declarations#iso32005
|Mandatory field(s) |none
|Standard |ISO/TS 32005
|Version |1
|URI |https://www.pdfa.org/resource/ISO-32005/
|Level |N/A
|Technology Reliance |ISO 32000-2
|===

EXAMPLE Conformance declaration for a PDF file conforming to this
document:

[source,xml]
----
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:pdfd="http://pdfa.org/declarations/">
    <pdfd:declarations>
      <rdf:Bag>
        <!-- Declaration for conformity with standard “ISO 32005” -->
        <rdf:li rdf:parseType="Resource">
          <pdfd:conformsTo>http://pdfa.org/declarations#iso32005</pdfd:conformsTo>
        </rdf:li>
      </rdf:Bag>
    </pdfd:declarations>
  </rdf:Description>
</rdf:RDF>
----