[[using-namespaces]]
== Using the PDF 1.7 namespace with the PDF 2.0 namespace

=== General

ISO 32000-2 permits the use of both the PDF 1.7 namespace and the
PDF 2.0 namespace but does not indicate how they are to be used together
in the same document. The following clauses clarify this usage.

NOTE ISO 32000-2 does not restrict the interaction of the two
namespaces.

PDF documents conforming to this document shall be versioned as PDF 2.0
using either the header or the value of the *Version* entry in the
document's catalog dictionary (see ISO 32000-2:2020, 7.7.2).

[[pdf17-standalone]]
=== PDF 1.7 as a standalone namespace

If all structure elements used in a given document are PDF 1.7 elements, either
explicitly, through the default standard structure namespace or role mapped to
an element in the default standard structure namespace, then the requirements of
ISO 32000-1 shall be used for their inclusion. In such cases, the use of
namespaces shall not be required and those structure elements are exempt from
the provisions specified in <<common-elements>>, <<unique-pdf2>> and
<<unique-pdf1.7>>.

If any document has structure elements that use a namespace other than the PDF
1.7 namespace or the default standard structure namespace, then that document
shall conform to the requirements specified in <<common-elements>>,
<<unique-pdf2>> and <<unique-pdf1.7>>.

[[common-elements]]
=== Elements defined in both the PDF 1.7 and PDF 2.0 namespace

A subset of the PDF 1.7 elements and the PDF 2.0 elements are common
between the two namespaces. All structure elements whose type is common
to both the PDF 1.7 namespace and the PDF 2.0 namespace shall use the
PDF 2.0 namespace and follow the inclusion rules defined in ISO
32000-2:2020, Annex L, and in <<declaration>> of this document (except as
exempted by <<pdf17-standalone>>).

[[unique-pdf2]]
=== Elements defined solely in the PDF 2.0 namespace

PDF 2.0 elements shall explicitly declare their namespace using the
PDF 2.0 namespace and may contain unique PDF 1.7 elements and PDF 2.0
elements, as defined in <<declaration>>.

NOTE: ISO 32000-2:2020, Annex M identifies the new elements that are
solely defined for the PDF 2.0 namespace.

[[unique-pdf1.7]]
=== Elements defined solely in the PDF 1.7 namespace

==== General

Unique PDF 1.7 elements may be included in a document. When such
structure elements are included (except as exempted in <<pdf17-standalone>>), those
elements shall conform to the requirements defined in <<declaration>> and may
be children of PDF 2.0 elements and may include unique PDF 1.7 elements
or PDF 2.0 elements.

NOTE: ISO 32000-2:2020, Annex M identifies the elements that are solely
defined for the PDF 1.7 namespace.

==== Permitted PDF 1.7 element types

===== General

ISO 32000-2 does not directly define the element types outside of the
PDF 2.0 namespace. Instead, it refers to the definition of those
elements in ISO 32000-1. To ensure consistency, unique PDF 1.7 elements
(except as exempted by <<pdf17-standalone>>) shall match the descriptions and follow the
inclusion rules specified in <<declaration>>.

===== Grouping structure elements

The unique PDF 1.7 elements that are a grouping element type are defined
in <<SST17GROUP>> and shall be the only PDF 1.7 namespace grouping elements
permissible in a document (except as exempted by <<pdf17-standalone>>).

[[SST17GROUP]]
.Standard structure types for unique PDF 1.7 grouping elements
[width="100%",cols="19%,81%",options="header",]
|===
|*Structure type* |*Description*
|Art |(Article) A relatively self-contained body of text constituting a
single narrative or exposition. Articles should be disjoint; that is,
they should not contain other articles as constituent elements.

|[[SST17GROUP-blockquote]]BlockQuote a|
(Block quotation) A portion of content quoted from another source other
than the surrounding content.

NOTE: The *BlockQuote* structure element groups larger units of quoted
content, see *Quote* (<<SST17INLINE-quote>>, "") for inline quotation.

NOTE: The *BlockQuote* structure element differs from the
*DocumentFragment* structure element, in that *DocumentFragment* implies
unchanged and contiguous portions of another document, whereas
*BlockQuote* often include modification or contextualization.
*BlockQuote* is permitted to both contain or be a child of
*DocumentFragment* (see <<BlockQuote-relationships>>).

NOTE: The source for a *BlockQuote* can include content from the same
document.

|TOC a|
(Table of contents) A list made up of table of contents item entries
(structure type *TOCI*) and/or other nested table of contents entries
(*TOC*).

A *TOC* entry that includes only *TOCI* entries represents a flat
hierarchy. A *TOC* entry that includes other nested *TOC* entries (and
possibly *TOCI* entries) represents a more complex hierarchy. Ideally,
the hierarchy of a top-level *TOC* entry reflects the structure of the
main body of the document.

NOTE: Lists of figures and tables, as well as bibliographies, can be
treated as tables of contents for purposes of the standard structure
types.

When parts of a *TOC* have descriptive text, that text shall use
*Caption* to identify its purpose. When multiple parts of the *TOC* have
descriptive text at the same level within that *TOC*, then *Part* shall
be used to subdivide that *TOC* into the described (captioned)
sub-parts, with each *Part* having its own *Caption*.

|TOCI |(Table of contents item) An individual entry within a table of
contents (*TOC*).

|Index |(Index) A sequence of entries containing identifying text
accompanied by reference elements (structure type *Reference*; see
<<SST17INLINE-reference>>) that point out occurrences of the specified text in the main
body of a document.

|Private |(Private element) A grouping element containing private
content belonging to the application producing it. The structural
significance of this element type is unspecified and shall be determined
entirely by the writer. Neither the *Private* element nor any of its
descendants (including content) have defined semantic significance and
may be ignored by processors, both when consuming the content and when
exporting to other document formats.

|NOTE: The definitions in this table are taken from ISO 32000-1, but have
been updated for clarity. |
|===

===== Inline-level structure elements

The unique PDF 1.7 elements that are an inline-level element type are
defined in <<SST17INLINE>> and shall be the only PDF 1.7 namespace inline-level
structure elements permissible in a document (except as exempted by
Clause <<pdf17-standalone>>).

[[SST17INLINE]]
.Standard structure types for unique PDF 1.7 inline-level structure elements
[width="100%",cols="19%,81%",options="header",]
|===
|*Structure type* |*Description*
|[[SST17INLINE-quote]]Quote a|
(Quotation) An inline portion of content quoted from another source
other than the surrounding content.

The quoted text should be contained inline within a single block-level
unit of content. This differs from the block-level element *BlockQuote*
(see <<SST17GROUP-blockquote>>), which consists of one or more complete paragraphs (or
other elements presented as if they were complete paragraphs).

|Note a|
(Note) An item of explanatory text, such as a footnote or an endnote,
that is referred to from within the body of the document. It may have a
label (structure type *Lbl*; see ISO 32000-2:2020, Table 368) as a
child.

The note may be included as a child of the structure element in the body
text that refers to it, or it may be included elsewhere (such as in an
endnotes section) and accessed by means of a reference (structure type
*Reference*).

Tagged PDF does not prescribe the placement of footnotes in the page
content order. They may be either inline or at the end of the page, at
the discretion of the conforming writer.

|[[SST17INLINE-reference]]Reference |(Reference) A citation to content elsewhere in the document.

|BibEntry a|
(Bibliography entry) A reference identifying the external source of some
cited content. It may contain a label (structure type *Lbl*; see ISO
32000-2:2020, Table 368) as a child.

Although a bibliography entry is likely to include component parts
identifying the cited content's author, work, publisher, and so forth,
no standard structure types are defined at this level of detail.

|Code |(Code) A fragment of computer program text.

|NOTE: The definitions in this table are taken from ISO 32000-1, but have
been updated for clarity. |
|===

=== Role mapping

Custom element types may be present in a document and shall have an
explicitly defined namespace except as exempted by <<pdf17-standalone>>.
