== Attributes

=== General

ISO 32000-2 defines a mechanism for applying structure attributes to
structure elements (see ISO 32000-2:2020, 14.7.6). While both ISO
32000-2 and ISO 32000-1 defined this mechanism, ISO 32000-2 extended it
to additionally make use of namespaces (see ISO 32000-2:2020,
Table 360). <<using-namespaces>> specifies the requirements for a file containing
structure attributes.

=== Attribute owners

Attribute owners (see ISO 32000-2:2020, Table 376) identify sets of
attributes that are available for use with structure elements. For each
attribute, attribute owners also restrict the structure element type
with which they may be used.

The attributes defined within the various attribute owners in ISO
32000-2 are a superset of those defined in ISO 32000-1. As such,
regardless of whether a given structure element is a unique PDF 1.7
element or a PDF 2.0 element, that structure element may use any
structure attribute defined in ISO 32000-2, as restricted by those
attributes' definition.

=== Attribute namespaces

As an alternative to attribute owners, ISO 32000-2 defines a mechanism
for identifying a namespace for a given set of attributes (see ISO
32000-2:2020, Table 360). Attribute objects identifying their owner as a
namespace may occur on any structure element regardless of that
structure element's namespace.