== Terms and definitions


=== interactive processor

{{processor}} that requires or allows human interaction with the content and
other objects contained in the document during the software's processing phase

NOTE: A file viewing tool is an example of an interactive processor; a raster
image processor is an example of a processor that is not interactive.

=== PDF

Portable Document Format

file format defined in <<ISO32000-2>>

=== PDF 1.7 namespace

standard structure namespace for PDF 1.7

as defined in <<ISO32000-1>>

=== PDF 2.0 namespace

standard structure namespace for PDF 2.0

as defined in <<ISO32000-2>>

=== PDF 1.7 element

standard structure element type defined in the namespace for PDF 1.7

as defined in <<ISO32000-1>>

=== PDF 2.0 element

standard structure element type defined in the namespace for PDF 2.0

as defined in <<ISO32000-2>>


=== processor

software application that is able to read and process conforming files

=== unique PDF 1.7 element

standard structure element whose type is defined solely in the {{PDF 1.7 namespace}}


=== writer

software application that is able to write conforming files

