== Parent-child relationships between the standard structure elements in the standard structure namespace for PDF 2.0 and PDF 1.7

=== General

ISO 32000-2 defines the standard structure element types within ISO
32000-2:2020, 14.8.4 and identifies the PDF 1.7 namespace and the
PDF 2.0 namespace in ISO 32000-2:2020, 14.8.6. ISO 32000-2:2020,
Annex L, specifies the requirements for hierarchical inclusion of the
PDF 2.0 elements.

<<mega-table>> extends the rules for hierarchical inclusion^[1]^ to both the
PDF 2.0 elements and PDF 1.7 elements.

NOTE: A compact representation of the hierarchical inclusion rules
defined in <<mega-table>> can be found in Reference [1].

[[mega-table]]
=== Hierarchical inclusion rules

This subclause defines the acceptable children of the standard structure
elements defined in the PDF 1.7 namespace and the PDF 2.0 namespace. PDF 1.7
elements and PDF 2.0 elements shall not have child or parent PDF 1.7 elements or
PDF 2.0 elements that are not explicitly listed in these tables.

The following tables provide these hiearchical inclusion rules:

include::../generated/parent-list.adoc[]

NOTE: The hierarchical rules defined in this clause describe the
elements that are permissible as children of each structure type.
However, further contextual restrictions are described in Clause 5 and
ISO 32000-2:2020, 14.8 “Tagged PDF”.

NOTE: The hierarchical rules included in this subclause extend those
found in ISO 32000-2:2020, Annex L, and can be considered complete for
all elements permitted by this document. These extensions pertain to
unique PDF 1.7 elements and their interaction with other PDF 1.7
elements and PDF 2.0 elements. These requirements fully conform to those
found in ISO 32000-2 and associated errata for PDF 2.0 elements.

These containment requirements shall also apply to structure elements
that are role mapped into the PDF 2.0 namespace or PDF 1.7 namespace
(except as exempted by <<pdf17-standalone>>). <<SSTVALID>> provides a legend for use in
interpreting the tables found in <<mega-table>>.

[[SSTVALID]]
.Legend for valid usage of structure types
[width="100%",cols="9%,91%",options="header",]
|===
|Value |Valid usage relative to other standard structure types
|ø |shall not occur

|ø* |shall not occur unless the parent element is used as a grouping
level element

|0..n |may be a child element with one or several occurrences, but is
not required to be present

|1..n |shall be present as a child element with one or several
occurrences

|0..1 |may occur, but not more than once

|‡ |for containment rules, refer to the respective structure element
type's description

|[a] |for specific provisions when and how these structure elements or
content can be contained inside a *Ruby* structure element, see ISO
32000-2:2020, 14.8.4.7.3

|[b] |for specific provisions when and how these structure elements or
content can be contained inside a *Warichu* structure element, see ISO
32000-2:2020, 14.8.4.7.3
|===

NOTE: StructTreeRoot refers to the structure tree root dictionary (see "ISO
32000-2:2020, Table 354 — Entries in the structure tree root") and is not the
name of a structure element.

NOTE: A content item refers to page content (see ISO 32000-2:2020, 14.8.2
“Tagged PDF and page content”) or PDF objects (see ISO 32000-2:2020, 14.7 “PDF
objects as content items”) and does not refer to the name of a structure element
type.

include::../generated/structure-relationships.adoc[]